// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgxpxnxcjsekfibdbowz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneHB4bnhjanNla2ZpYmRib3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDE4MTUsImV4cCI6MjA2MDYxNzgxNX0.x0ZIWDbjtjF9KmzilbGhZh1IuyGYfv_ycYCBBnT0UPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);